apiVersion: v1
kind: Service
metadata:
  labels:
    app: twitter-analysis
  name: twitter-analysis-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/twitter-analysis-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: twitter-analysis
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}